target ‘lolyhub’ do
  pod 'IQKeyboardManagerSwift'

use_frameworks!
pod 'LUExpandableTableView'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'Google/SignIn'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'MBProgressHUD', '~> 1.0.0'
end




